<?php
/****************************************
*               Russian                 *
****************************************/
$t['ru'] = array(
    // admin/index.php
    'login_header' => 'Панель администратора',
    'login_textbox' => 'Пароль',
    'login_button' => 'Войти',
	'message_success' => 'Изменения были сохранены.',
	'message_error' => 'Ошибка. Нет прав на запись в файл config.php',
	'page_title' => 'Панель администратора',
	'menu_update_database' => 'Обновить базу данных',
    'menu_manager' => 'Менеджер базы',
	'menu_exit' => 'Выйти',
	'header_change_password' => 'Смена пароля администратора',
	'label_new_password' => 'Новый пароль ',
	'header_change_translate' => 'Выбор перевода скрипта',
    'label_lang_ukranian' => 'Украинский',
	'label_lang_english' => 'Английский',
	'label_lang_russian' => 'Русский',
	'label_lang_spanish' => 'Испанский',
	'label_lang_german' => 'Немецкий',
	'label_lang_french' => 'Французски',
	'header_change_address_to_form_search' => 'Смена адреса на формы поиска шин и дисков по параметрам',
	'label_tire_load_index' => 'Индекс нагрузки',
	'label_tire_speed_index' => 'Индекс скорости',
	'label_tire_width' => 'Ширина шины',
	'label_tire_height' => 'Высота шины',
	'label_tire_diameter' => 'Диаметр шины',
	'label_wheel_diameter' => 'Диаметр диска',
	'label_wheel_pcd' => 'PCD диска',
	'label_wheel_pcd_length_of_diameter' => 'Диаметр сверловки',
	'label_wheel_pcd_number_of_studs' => 'Количество отверстий под крепления диска (болты/гайки)',
	'label_wheel_dia' => 'Внутренний диаметр диска',
	'label_wheel_fastener_size' => 'Параметры крепления диска (Гайки/Болта)',
	'label_wheel_rim' => 'Ширина профиля диска',
	'label_wheel_et' => 'Вылет диска',
	'note_all_filds_not_depend' => '* Любое поле может быть пропущено в адресе.',
	'header_change_database_properties' => 'Изменить настройки подключения к базе данных',
	'label_note_get_connection' => 'Данные подключения к базе данных уточняйте у своего хостинг провайдера.',
	'label_database_address' => 'Хост/Адрес',
	'label_database_port' => 'Порт',
	'label_database_user' => 'Имя пользователя',
	'label_database_password' => 'Пароль',
	'label_database_name' => 'Имя базы данных',
	'label_database_adapter' => 'Адаптер подключения к базе данных',
    'label_database_cache' => 'Использовать кеш',
	'button_save_config' => 'Сохранить параметры',

    // form.php
    'form_header' => 'Подбор автомобильных шин и дисков по марке авто',
    'select_type_vehicle' => 'Тип транспорта:',
    'select_brand' => 'Марка:',
    'select_model' => 'Модель:',
    'select_year' => 'Год выпуска:',
    'select_modification' => 'Модификация:',
    'tv_passanger' => 'Легковой автомобиль',
    'tv_truck' => 'Грузовая техника',
    'tv_special' => 'Спецтехника',
    'tv_moto' => 'Мототехника',
    'search_all' => 'Подобрать',
    'search_only_tires' => 'Подобрать шины',
    'search_only_wheels' => 'Подобрать диски',

    // results.php
    'res_nothing' => 'Нет данных по выбранному авто.',
    'res_tires_for_auto' => 'Шины для автомобиля',
    'res_speed_index' => 'Индекс скорости:',
    'res_load_index' => 'Индекс нагрузки:',
    'res_manufacture_complect' => 'Заводская комплектация',
    'res_alt_complect' => 'Варианты замены',
    'res_tuning' => 'Тюнинг',
    'res_wheels_for_auto' => 'Диски для автомобиля',
    'res_pcd' => 'Сверловка (PCD):',
    'res_dia' => 'Dia:',
    'res_fastener' => 'Крепление:',
    'res_tuning' => 'Тюнинг',
    'res_tires_wheels_for_auto' => 'Шины и диски для автомобиля',
    'res_tires' => 'Шины',
    'res_wheels' => 'Диски',
    'res_front_axle' => 'Передняя ось',
    'res_rear_axle' => 'Задняя ось',
    'res_tuning_diff_width' => 'Тюнинг (Разноширокие колеса)',
    'res_tuning_low_tires' => 'Тюнинг (Низкопрофильные шины)',
    'res_both_axles' => 'Обе оси',

    // lib.php
    'lib_some_size' => 'Размер шины совпадает с заводским размером шины.',
    'lib_size' => 'Размер шины на',
    'lib_less' => 'мм. меньше заводского размера шины',
    'lib_bigger' => 'мм. больше заводского размера шины',
);


/****************************************
*               Ukranian                *
****************************************/
$t['ua'] = array(
    // admin/index.php
    'login_header' => 'Панель адміністратора',
    'login_textbox' => 'Пароль',
    'login_button' => 'Ввійти',
    'message_success' => 'Зміни були збережені.',
    'message_error' => 'Помилка. Немає прав на запис в файл config.php',
    'page_title' => 'Панель адміністратора',
    'menu_update_database' => 'Оновити базу даних',
    'menu_manager' => 'Менеджер бази',
    'menu_exit' => 'Вийти',
    'header_change_password' => 'Зміна пароля адміністратора',
    'label_new_password' => 'Новий пароль',
    'header_change_translate' => 'Вибір перекладу',
    'label_lang_ukranian' => 'Український',
    'label_lang_english' => 'Англійська',
    'label_lang_russian' => 'Російська',
    'label_lang_spanish' => 'Іспанська ',
    'label_lang_german' => 'Німецький',
    'label_lang_french' => 'Французьки',
    'header_change_address_to_form_search' => 'Зміна адреси на форми пошуку шин і дисків за параметрами',
    'label_tire_load_index' => 'Індекс навантаження',
    'label_tire_speed_index' => 'Індекс швидкості',
    'label_tire_width' => 'Ширина шини',
    'label_tire_height' => 'Висота шини',
    'label_tire_diameter' => 'Діаметр шини',
    'label_wheel_diameter' => 'Діаметр диска',
    'label_wheel_pcd' => 'PCD діска',
    'label_wheel_pcd_length_of_diameter' => 'Діаметр сверловки',
    'label_wheel_pcd_number_of_studs' => 'Кількість отворів під кріплення диска (болти / гайки)',
    'label_wheel_dia' => 'Внутрішній діаметр диска',
    'label_wheel_fastener_size' => 'Параметри кріплення диска (Гайки / Болта)',
    'label_wheel_rim' => 'Ширина профілю диска',
    'label_wheel_et' => 'Виліт диска',
    'note_all_filds_not_depend' => '* Будь-яке поле може бути пропущено в адресі.',
    'header_change_database_properties' => 'Змінити налаштування підключення до бази даних',
    'label_note_get_connection' => 'Дані підключення до бази даних уточнюйте у свого хостинг провайдера.',
    'label_database_address' => 'Хост/Адреса',
    'label_database_port' => 'Порт',
    'label_database_user' => 'Ім\'я користувача',
    'label_database_password' => 'Пароль',
    'label_database_name' => 'Ім\'я бази даних',
    'label_database_adapter' => 'Адаптер підключення до бази даних',
    'label_database_cache' => 'Використовувати кеш',
    'button_save_config' => 'Зберегти параметри',

    // form.php
    'form_header' => 'Підбір автомобільних шин і дисків по марці авто',
    'select_type_vehicle' => 'Тип транспорту:',
    'select_brand' => 'Марка:',
    'select_model' => 'Модель:',
    'select_year' => 'Рік випуску:',
    'select_modification' => 'Модифікація:',
    'tv_passanger' => 'Легковий автомобіль',
    'tv_truck' => 'Вантажна техніка',
    'tv_special' => 'Спецтехніка',
    'tv_moto' => 'Мототехніка',
    'search_all' => 'Підібрати',
    'search_only_tires' => 'Підібрати шини',
    'search_only_wheels' => 'Підібрати диски',

    // results.php
    'res_nothing' => 'Немає даних по вибраному авто.',
    'res_tires_for_auto' => 'Шини для автомобіля',
    'res_speed_index' => 'Індекс швидкості:',
    'res_load_index' => 'Індекс навантаження:',
    'res_manufacture_complect' => 'Заводська комплектація',
    'res_alt_complect' => 'Варіанти заміни',
    'res_tuning' => 'Тюнінг',
    'res_wheels_for_auto' => 'Диски для автомобіля',
    'res_pcd' => 'Сверловка (PCD):',
    'res_dia' => 'Dia:',
    'res_fastener' => 'Кріплення:',
    'res_tires_wheels_for_auto' => 'Шини і диски для автомобіля',
    'res_tires' => 'Шини',
    'res_wheels' => 'Диски',
    'res_front_axle' => 'Передня вісь',
    'res_rear_axle' => 'Задня вісь',
    'res_tuning_diff_width' => 'Тюнінг (різноширокій колеса)',
    'res_tuning_low_tires' => 'Тюнінг (Низькопрофільні шини)',
    'res_both_axles' => 'Обидві осі',

    // lib.php
    'lib_some_size' => 'Розмір шини збігається з заводським розміром шини.',
    'lib_size' => 'Розмір шини на',
    'lib_less' => 'мм. менше заводського розміру шини',
    'lib_bigger' => 'мм. більше заводського розміру шини',
);


/****************************************
*               English                 *
****************************************/
$t['en'] = array(
    // admin/index.php
    'login_header' => 'Administrator panle',
    'login_textbox' => 'Password',
    'login_button' => 'Sugn in',
	'message_success' => 'Changes was saved.',
	'message_error' => 'Error. You don\'t have permission write to file config.php',
	'page_title' => 'Administrator area',
	'menu_update_database' => 'Update database',
    'menu_manager' => 'Manager DB',
	'menu_exit' => 'Exit',
	'header_change_password' => 'Change admin password',
	'label_new_password' => 'New password ',
	'header_change_translate' => 'Select translate',
    'label_lang_ukranian' => 'Ukranian',
	'label_lang_english' => 'English',
	'label_lang_russian' => 'Russian',
	'label_lang_spanish' => 'Spanish',
	'label_lang_german' => 'German',
	'label_lang_french' => 'Franch',
	'header_change_address_to_form_search' => 'Change address to forms search tires and wheels by properties',
	'label_tire_load_index' => 'Load index',
	'label_tire_speed_index' => 'Speed index',
	'label_tire_width' => 'Tire width',
	'label_tire_height' => 'Tire height',
	'label_tire_diameter' => 'Tire diameter',
	'label_wheel_diameter' => 'Wheel diameter',
	'label_wheel_pcd' => 'Wheel PCD',
	'label_wheel_pcd_length_of_diameter' => 'Wheel PCD diameter',
	'label_wheel_pcd_number_of_studs' => 'Wheel PCD number studs (bolt/nut)',
	'label_wheel_dia' => 'Dia',
	'label_wheel_fastener_size' => 'Wheel fastener size (bolt/nut)',
	'label_wheel_rim' => 'Wheel rim',
	'label_wheel_et' => 'Wheel ET',
	'note_all_filds_not_depend' => '* Any field can be empty or skip.',
	'header_change_database_properties' => 'Change connection options to database',
	'label_note_get_connection' => 'Propertis connection to database you can clarify on hosting provider.',
	'label_database_address' => 'Host/Address',
	'label_database_port' => 'Port',
	'label_database_user' => 'User name',
	'label_database_password' => 'Password',
	'label_database_name' => 'Database name',
	'label_database_adapter' => 'Database adapter',
    'label_database_cache' => 'Use the cache',
	'button_save_config' => 'Save properties',

    // form.php
    'form_header' => 'Fitting tires and wheels by auto',
    'select_type_vehicle' => 'Type of vehicle:',
    'select_brand' => 'Brand:',
    'select_model' => 'Model:',
    'select_year' => 'Year:',
    'select_modification' => 'Modification:',
    'tv_passanger' => 'Passanger',
    'tv_truck' => 'Truck',
    'tv_special' => 'Special',
    'tv_moto' => 'Moto',
    'search_all' => 'Seach',
    'search_only_tires' => 'Search tires',
    'search_only_wheels' => 'Search wheels',

    // results.php
    'res_nothing' => 'Nothing by your auto.',
    'res_tires_for_auto' => 'Tires for auto',
    'res_speed_index' => 'Speed index:',
    'res_load_index' => 'Load index:',
    'res_manufacture_complect' => 'Manufacturer complectation',
    'res_alt_complect' => 'Alternative sizes',
    'res_tuning' => 'Tuning',
    'res_wheels_for_auto' => 'Wheels for auto',
    'res_pcd' => 'PCD:',
    'res_dia' => 'Dia:',
    'res_fastener' => 'Fastener:',
    'res_tires_wheels_for_auto' => 'Tires and wheels for auto',
    'res_tires' => 'Tires',
    'res_wheels' => 'Wheels',
    'res_front_axle' => 'Front axle',
    'res_rear_axle' => 'Rear axle',
    'res_tuning_diff_width' => 'Tuning (diff widhts)',
    'res_tuning_low_tires' => 'TUning (low tires)',
    'res_both_axles' => 'Both axles',

    // lib.php
    'lib_some_size' => 'Tire size same as the factory tire size.',
    'lib_size' => 'Size Tires',
    'lib_less' => 'mm. less than the factory tire size',
    'lib_bigger' => 'mm. more factory tire size',
);



/****************************************
*               France                  *
****************************************/
$t['fr'] = array(
    // admin/index.php
    'login_header' => 'Panneau d\'administration ',
    'login_textbox' => 'Mot de passe ',
    'login_button' => 'Connectez-vous',
	'message_success' => 'Des modifications ont été enregistrées.',
	'message_error' => 'Erreur. Aucune autorisation d\'écriture dans le fichier config.php',
	'page_title' => 'panneau d\'administration',
	'menu_update_database' => 'Mise à jour de base de données',
    'menu_manager' => 'Manager DB',
	'menu_exit' => 'Déconnexion',
	'header_change_password' => 'Changer le mot de passe administrateur',
	'label_new_password' => 'le nouveau mot de passe ',
	'header_change_translate' => 'Sélections registres de transfert',
    'label_lang_ukranian' => 'Ukranian',
	'label_lang_english' => 'Anglais',
	'label_lang_russian' => 'Russie',
	'label_lang_spanish' => 'espagnol',
	'label_lang_german' => 'allemand',
	'label_lang_french' => 'français',
	'header_change_address_to_form_search' => 'Formulaire de changement d\'adresse à roues de la recherche et des pneus sur les paramètres',
	'label_tire_load_index' => 'Indice de charge',
	'label_tire_speed_index' => 'Индекс скорости',
	'label_tire_width' => 'Indice de vitesse',
	'label_tire_height' => 'la hauteur du pneu',
	'label_tire_diameter' => 'le diamètre du pneumatique',
	'label_wheel_diameter' => 'le diamètre du disque',
	'label_wheel_pcd' => 'disque PCD',
	'label_wheel_pcd_length_of_diameter' => 'diamètre du Forez',
	'label_wheel_pcd_number_of_studs' => 'Nombre de trous pour la fixation du disque (vis / écrous)',
	'label_wheel_dia' => 'Le diamètre intérieur du disque',
	'label_wheel_fastener_size' => 'Options de montage du disque (écrous / boulons)',
	'label_wheel_rim' => 'Lecteur de Largeur',
	'label_wheel_et' => 'Décalage',
	'note_all_filds_not_depend' => '* Les champs peuvent être omis dans l\'adresse.',
	'header_change_database_properties' => 'Modifiez les paramètres pour se connecter à la base de données',
	'label_note_get_connection' => 'Ceux-ci se connectent à la vérification de la base de données avec votre fournisseur d\'hébergement.',
	'label_database_address' => 'Hôte / Adresse',
	'label_database_port' => 'Port',
	'label_database_user' => 'nom d\'utilisateur',
	'label_database_password' => 'mot de passe',
	'label_database_name' => 'Le nom de la base de données',
	'label_database_adapter' => 'Adaptateur pour se connecter à la base de données',
    'label_database_cache' => 'Utilisez le cache',
	'button_save_config' => 'Enregistrer les paramètres',

    // form.php
    'form_header' => 'Sélection des pneus et des roues de voiture Marques',
    'select_type_vehicle' => 'Type de véhicule:',
    'select_brand' => 'Fabricant:',
    'select_model' => 'Modèle:',
    'select_year' => 'Année:',
    'select_modification' => 'Modification:',
    'tv_passanger' => 'Voitures de tourisme',
    'tv_truck' => 'Véhicules industriels',
    'tv_special' => 'L\'équipement spécial',
    'tv_moto' => 'Moto',
    'search_all' => 'Ramasser',
    'search_only_tires' => 'Trouvez des pneus',
    'search_only_wheels' => 'Choisissez des disques',

    // results.php
    'res_nothing' => 'Aucune donnée sur le véhicule sélectionné.',
    'res_tires_for_auto' => 'Pneus pour la voiture',
    'res_speed_index' => 'Indice de vitesse:',
    'res_load_index' => 'Indice de charge:',
    'res_manufacture_complect' => 'Equipements d\'usine',
    'res_alt_complect' => 'Les options de remplacement',
    'res_tuning' => 'Tuning',
    'res_wheels_for_auto' => 'Roues pour voiture',
    'res_pcd' => 'Portage (PCD):',
    'res_dia' => 'Dia:',
    'res_fastener' => 'Montage:',
    'res_tires_wheels_for_auto' => 'Les pneus et les roues',
    'res_tires' => 'Bus',
    'res_wheels' => 'Roues',
    'res_front_axle' => 'Essieu avant',
    'res_rear_axle' => 'Essieu arrière',
    'res_tuning_diff_width' => 'Tuning (roues Raznoshirokie)',
    'res_tuning_low_tires' => 'Tuning (pneus à profil bas)',
    'res_both_axles' => 'Les deux axes',

    // lib.php
    'lib_some_size' => 'Même taille que la taille des pneus de l\'usine de pneus.',
    'lib_size' => 'Taille des pneus',
    'lib_less' => 'mm. inférieure à la dimension du pneumatique de l\'usine',
    'lib_bigger' => 'mm. plus la taille des pneus à l\'usine',
);



/****************************************
*               German                  *
****************************************/
$t['de'] = array(
    // admin/index.php
    'login_header' => 'Admin panel',
    'login_textbox' => 'Passwort',
    'login_button' => 'Anmelden',
	'message_success' => 'Änderungen wurden gespeichert.',
	'message_error' => 'Fehler. Keine Berechtigung um die Datei zu schreiben config.php',
	'page_title' => 'Admin-Panel',
	'menu_update_database' => 'Update-Datenbank',
    'menu_manager' => 'Manager DB',
	'menu_exit' => 'abmelden',
	'header_change_password' => 'Ändern Sie das Administrator-Passwort',
	'label_new_password' => 'Das neue Passwort ',
	'header_change_translate' => 'Selections Transfer',
    'label_lang_ukranian' => 'Ukranian',
	'label_lang_english' => 'Englisch',
	'label_lang_russian' => 'Russisch',
	'label_lang_spanish' => 'Spanisch',
	'label_lang_german' => 'Deutsch',
	'label_lang_french' => 'Französisch',
	'header_change_address_to_form_search' => 'Adressänderung Form zur Suche Räder und Reifen auf den Parametern',
	'label_tire_load_index' => 'Last-Index',
	'label_tire_speed_index' => 'Speed ​​Index',
	'label_tire_width' => 'Busbreite',
	'label_tire_height' => 'die Höhe des Reifens',
	'label_tire_diameter' => 'der Durchmesser des Reifens',
	'label_wheel_diameter' => 'der Durchmesser der Scheibe',
	'label_wheel_pcd' => 'PCD Disc',
	'label_wheel_pcd_length_of_diameter' => 'Durchmesser von Drill',
	'label_wheel_pcd_number_of_studs' => 'Anzahl der Bohrungen zur Befestigung der Scheibe (Schrauben / Muttern)',
	'label_wheel_dia' => 'Der Innendurchmesser der Scheibe',
	'label_wheel_fastener_size' => 'Optionen mounten der Festplatte (Schrauben / Muttern)',
	'label_wheel_rim' => 'Breite Laufwerk',
	'label_wheel_et' => 'Offset',
	'note_all_filds_not_depend' => '* Jedes Feld kann in der Adresse weggelassen werden.',
	'header_change_database_properties' => 'Ändern Sie die Einstellungen, um die Verbindung zur Datenbank',
	'label_note_get_connection' => 'Diese in der Datenbank-Check mit Ihrem Hosting-Provider zu verbinden.',
	'label_database_address' => 'Host / Adresse',
	'label_database_port' => 'Hafen',
	'label_database_user' => 'Benutzername',
	'label_database_password' => 'Kennwort',
	'label_database_name' => 'Der Name der Datenbank',
	'label_database_adapter' => 'Adapter zur Verbindung mit der Datenbank',
    'label_database_cache' => 'Verwenden Sie den Cache',
	'button_save_config' => 'Einstellungen speichern',

    // form.php
    'form_header' => 'Auswahl von Autoreifen und Felgen von Automarken',
    'select_type_vehicle' => 'Fahrzeugtyp:',
    'select_brand' => 'Hersteller:',
    'select_model' => 'Modell:',
    'select_year' => 'Jahr:',
    'select_modification' => 'Modifikation:',
    'tv_passanger' => 'PKW',
    'tv_truck' => 'Nutzfahrzeuge',
    'tv_special' => 'Sonderausstattung',
    'tv_moto' => 'Motorräder',
    'search_all' => 'Abholen',
    'search_only_tires' => 'Finden Sie Ihren Reifen',
    'search_only_wheels' => 'Pick up Platten',

    // results.php
    'res_nothing' => 'Keine Daten auf dem ausgewählten Auto.',
    'res_tires_for_auto' => 'Reifen für Autos',
    'res_speed_index' => 'Geschwindigkeitsindex:',
    'res_load_index' => 'Lastindex:',
    'res_manufacture_complect' => 'Betriebseinrichtungen',
    'res_alt_complect' => 'Austausch-Optionen',
    'res_tuning' => 'Tuning',
    'res_wheels_for_auto' => 'Räder für Auto',
    'res_pcd' => 'Portierung (PCD):',
    'res_dia' => 'Dia:',
    'res_fastener' => 'Montage:',
    'res_tires_wheels_for_auto' => 'Reifen und Räder',
    'res_tires' => 'Bus',
    'res_wheels' => 'Räder',
    'res_front_axle' => 'Vorderachse',
    'res_rear_axle' => 'Hinterachse',
    'res_tuning_diff_width' => 'Tuning (Raznoshirokie Räder)',
    'res_tuning_low_tires' => 'Tuning (Niederquerschnittsreifen)',
    'res_both_axles' => 'Beide Achsen',

    // lib.php
    'lib_some_size' => 'Reifengröße gleich der Fabrik Reifengröße.',
    'lib_size' => 'Größe Reifen',
    'lib_less' => 'mm. weniger als die Werksreifengröße',
    'lib_bigger' => 'mm. mehr Fabrik Reifengröße',
);



/****************************************
*               Spanish                 *
****************************************/
$t['es'] = array(
    // admin/index.php=
    'login_header' => 'Panel de Administración',
    'login_textbox' => 'Contraseña ',
    'login_button' => 'Registrarse',
	'message_success' => 'Los cambios se han guardado.',
	'message_error' => 'Error. No hay permiso de escritura en el archivo config.php',
	'page_title' => 'panel de administración',
	'menu_update_database' => 'Database Update',
    'menu_manager' => 'Manager DB',
	'menu_exit' => 'finalizar la sesión',
	'header_change_password' => 'Cambiar la contraseña del administrador',
	'label_new_password' => 'La nueva contraseña ',
	'header_change_translate' => 'Registros de transferencia',
    'label_lang_ukranian' => 'Ukranian',
	'label_lang_english' => 'Inglés',
	'label_lang_russian' => 'ruso',
	'label_lang_spanish' => 'español',
	'label_lang_german' => 'alemán',
	'label_lang_french' => 'francés',
	'header_change_address_to_form_search' => 'Cambio de dirección a las ruedas de búsqueda y los neumáticos en los parámetros',
	'label_tire_load_index' => 'Índice de carga',
	'label_tire_speed_index' => 'Índice de velocidad',
	'label_tire_width' => 'Ancho de bus',
	'label_tire_height' => 'la altura de la llanta',
	'label_tire_diameter' => 'el diámetro de la llanta',
	'label_wheel_diameter' => 'el diámetro del disco',
	'label_wheel_pcd' => 'disco PCD',
	'label_wheel_pcd_length_of_diameter' => 'Diámetro de la perforación',
	'label_wheel_pcd_number_of_studs' => 'Número de agujeros para el montaje del disco (pernos / tuercas)',
	'label_wheel_dia' => 'El diámetro interior del disco',
	'label_wheel_fastener_size' => 'Opciones de montaje del disco (tuercas / pernos)',
	'label_wheel_rim' => 'Unidad de ancho',
	'label_wheel_et' => 'offset',
	'note_all_filds_not_depend' => '* Cualquier campo puede omitirse en la dirección.',
	'header_change_database_properties' => 'Cambiar los ajustes para conectarse a la base de datos',
	'label_note_get_connection' => 'Estos se conectan a la verificación de la base de datos con su proveedor de hosting.',
	'label_database_address' => 'Host / Dirección',
	'label_database_port' => 'puerto',
	'label_database_user' => 'nombre de usuario',
	'label_database_password' => 'contraseña',
	'label_database_name' => 'El nombre de la base',
	'label_database_adapter' => 'Adaptador para conectarse a la base de datos',
    'label_database_cache' => 'Utilice la caché',
	'button_save_config' => 'Guardar configuración',

    // form.php
    'form_header' => 'La selección de neumáticos y llantas de las marcas de coches',
    'select_type_vehicle' => 'Tipo de vehículo:',
    'select_brand' => 'Fabricante:',
    'select_model' => 'Modelo:',
    'select_year' => 'Año:',
    'select_modification' => 'Modificación:',
    'tv_passanger' => 'Automóviles de turismo',
    'tv_truck' => 'Maquinarias de carga',
    'tv_special' => 'Equipos especiales',
    'tv_moto' => 'Motocicletas',
    'search_all' => 'Recoger',
    'search_only_tires' => 'Encuentra los neumáticos',
    'search_only_wheels' => 'Recoge los discos',

    // results.php
    'res_nothing' => 'No hay datos sobre el vehículo seleccionado.',
    'res_tires_for_auto' => 'Neumáticos para coche',
    'res_speed_index' => 'Índice Velocidad:',
    'res_load_index' => 'Índice de carga:',
    'res_manufacture_complect' => 'Equipos de fábrica',
    'res_alt_complect' => 'Las opciones de reemplazo',
    'res_tuning' => 'Sintonización',
    'res_wheels_for_auto' => 'Ruedas para el coche',
    'res_pcd' => 'Portar (PCD):',
    'res_dia' => 'Dia:',
    'res_fastener' => 'Montaje:',
    'res_tires_wheels_for_auto' => 'Neumáticos y ruedas',
    'res_tires' => 'Autobús',
    'res_wheels' => 'Ruedas',
    'res_front_axle' => 'Eje delantero',
    'res_rear_axle' => 'Eje trasero',
    'res_tuning_diff_width' => 'Sintonía (ruedas Raznoshirokie)',
    'res_tuning_low_tires' => 'Sintonía (neumáticos de perfil bajo)',
    'res_both_axles' => 'Ambos ejes',

    // lib.php
    'lib_some_size' => 'Tamaño del neumático mismo que el tamaño de los neumáticos de la fábrica.',
    'lib_size' => 'Tamaño de las cubiertas',
    'lib_less' => 'mm. menor que el tamaño de los neumáticos de fábrica',
    'lib_bigger' => 'mm. más el tamaño de los neumáticos de fábrica',
);
?>
